apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
# PRODUCT SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-2
      containers:
        - name: product-service
          image: ghcr.io/madushanka-devops/microservices-product:0.0.41
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: staging
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
# CART SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-2
      containers:
        - name: cart-service
          image: ghcr.io/madushanka-devops/microservices-cart:0.0.41
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: staging
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# FRONTEND
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-2
      containers:
        - name: frontend
          image: ghcr.io/madushanka-devops/microservices-frontend:0.0.41
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: staging
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
# CORRECTED INGRESS (No Rewrite)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microstore-ingress
  namespace: staging
  # Annotations removed so paths are passed through as-is
spec:
  ingressClassName: nginx
  rules:
    - host: staging.microstore.local
      http:
        paths:
          # NGINX matches longest path first, so these specific API routes take precedence
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 5001
          - path: /api/cart
            pathType: Prefix
            backend:
              service:
                name: cart-service
                port:
                  number: 8080
          # Catch-all for the frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
